# wrangler.toml

name = "real-time"
main = "src/index.ts"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]

# Cấu hình D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "chat-app"
database_id = "81df4afd-7b2e-426c-9e7e-c922b8d85f67"

# Cấu hình Durable Objects


# Các phần bị comment trong JSON được giữ nguyên dưới dạng comment trong TOML
# vars.MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[[kv_namespaces]] 
   binding = "KV"
  id = "a65cdf00ca9a41b5b2d38c70ffe5aa29" 


[env]
  DATABASE_URL = "file:./dev.db"
  JWT_SECRET = "your-secret-here"

[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "NOTIFICATION_ROOM"
class_name = "NotificationRoom"
[durable_objects]

# ✅ Thêm phần này nếu chưa có:
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
[[migrations]]
tag = "v1"
new_sqlite_classes = ["NotificationRoom"]

[vars]
CLOUDINARY_CLOUD_NAME="de0zslyf7"
CLOUDINARY_API_KEY="225258554655337"
CLOUDINARY_API_SECRET="FjIBVw9G8nfGgeM4XsE56-DJNT0"
CLOUDINARY_UPLOAD_PRESET = "unsigned_upload"

