export enum MessageType {
  SEND_MESSAGE = "SEND_MESSAGE",
  TYPING = "TYPING",
  REQUEST_HISTORY = "REQUEST_HISTORY",
  MARK_AS_READ = "MARK_AS_READ",
  HISTORY = "HISTORY",
  MESSAGES_READ = "MESSAGES_READ",
}
